name: Build and Push Docker Images to ECR

on:
  push:
    branches: [ "master" ]  
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: us-east-1

      # Build and Push Webapp Image
      - name: Build Webapp Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: webapp
          IMAGE_TAG: v0.1
        run: |
          docker build -t $ECR_REGISTRY.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_WEBAPP:latest -f Dockerfile .

      - name: Push Webapp Image to ECR
        run: |
          docker push $ECR_REGISTRY.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_WEBAPP:latest

      # Build and Push MySQL Image
      - name: Build MySQL Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: mysql
          IMAGE_TAG: v0.1
        run: |
          docker build -t $ECR_REGISTRY.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_MYSQL:latest -f Dockerfile_mysql .

      - name: Push MySQL Image to ECR
        run: |
          docker push $ECR_REGISTRY.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_MYSQL:latest
